# Generated by Django 3.2.6 on 2021-12-18 17:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0003_remove_bootcamp_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
